//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS.Internal.Properties
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MS.Internal.Properties", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection of adorners for this element.
        /// </summary>
        internal static string AdornerNodeAutomationPeer_HelpText {
            get {
                return ResourceManager.GetString("AdornerNodeAutomationPeer_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adorners.
        /// </summary>
        internal static string AdornerNodeAutomationPeer_ItemType {
            get {
                return ResourceManager.GetString("AdornerNodeAutomationPeer_ItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adorners.
        /// </summary>
        internal static string AdornerNodeAutomationPeer_Name {
            get {
                return ResourceManager.GetString("AdornerNodeAutomationPeer_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Factor {1} Offset {2}.
        /// </summary>
        internal static string AdornerPlacement_ToString {
            get {
                return ResourceManager.GetString("AdornerPlacement_ToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designer UI Element..
        /// </summary>
        internal static string DesignerItemAutomationPeer_LocalizedControlType {
            get {
                return ResourceManager.GetString("DesignerItemAutomationPeer_LocalizedControlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The WPF Designer design surface.
        /// </summary>
        internal static string DesignerViewAutomationPeer_HelpText {
            get {
                return ResourceManager.GetString("DesignerViewAutomationPeer_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DesignerView.
        /// </summary>
        internal static string DesignerViewAutomationPeer_ItemType {
            get {
                return ResourceManager.GetString("DesignerViewAutomationPeer_ItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WPF Designer.
        /// </summary>
        internal static string DesignerViewAutomationPeer_Name {
            get {
                return ResourceManager.GetString("DesignerViewAutomationPeer_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adorner already has a parent..
        /// </summary>
        internal static string Error_AdornerHasParent {
            get {
                return ResourceManager.GetString("Error_AdornerHasParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The adorner is not currently parented to this element..
        /// </summary>
        internal static string Error_AdornerNotParentedToThisAdornerLayer {
            get {
                return ResourceManager.GetString("Error_AdornerNotParentedToThisAdornerLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; must be of type &apos;{1}&apos;..
        /// </summary>
        internal static string Error_ArgIncorrectType {
            get {
                return ResourceManager.GetString("Error_ArgIncorrectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; must be a type that is or derives from &apos;{1}&apos;..
        /// </summary>
        internal static string Error_ArgIncorrectTypeValue {
            get {
                return ResourceManager.GetString("Error_ArgIncorrectTypeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert Value to string..
        /// </summary>
        internal static string Error_CannotConvertValueToString {
            get {
                return ResourceManager.GetString("Error_CannotConvertValueToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update Value from StringValue..
        /// </summary>
        internal static string Error_CannotUpdateValueFromStringValue {
            get {
                return ResourceManager.GetString("Error_CannotUpdateValueFromStringValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate cannot be called on an active transacted task.  Either call Revert or Complete instead..
        /// </summary>
        internal static string Error_CantDeactivateActiveTransactedTask {
            get {
                return ResourceManager.GetString("Error_CantDeactivateActiveTransactedTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A DesignerView already exists within this editing context.  To create an additional designer view you must create a new context item layer first..
        /// </summary>
        internal static string Error_ContextHasView {
            get {
                return ResourceManager.GetString("Error_ContextHasView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The context item type &apos;{0}&apos; derives from the base item type of &apos;{1}&apos;.  Always pass a the base context item type..
        /// </summary>
        internal static string Error_DerivedContextItem {
            get {
                return ResourceManager.GetString("Error_DerivedContextItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DesignerActionProviders &apos;{0}&apos; and &apos;{1}&apos; are both attempting to provide the same instance of DesignerActionItem &apos;{2}&apos;.  This is illegal..
        /// </summary>
        internal static string Error_DesignerActionItemSharing {
            get {
                return ResourceManager.GetString("Error_DesignerActionItemSharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The editing context cannot be disposed while the designer view is handling a command..
        /// </summary>
        internal static string Error_DisposingDuringCall {
            get {
                return ResourceManager.GetString("Error_DisposingDuringCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An item for &apos;{0}&apos; already exists in the collection..
        /// </summary>
        internal static string Error_DuplicateItem {
            get {
                return ResourceManager.GetString("Error_DuplicateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service &apos;{0}&apos; has already been published by another object..
        /// </summary>
        internal static string Error_DuplicateService {
            get {
                return ResourceManager.GetString("Error_DuplicateService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ModelEditingScope has already been reverted..
        /// </summary>
        internal static string Error_EditingScopeReverted {
            get {
                return ResourceManager.GetString("Error_EditingScopeReverted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ModelEditingScope has already been completed..
        /// </summary>
        internal static string Error_EdtingScopeCompleted {
            get {
                return ResourceManager.GetString("Error_EdtingScopeCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more values contained in the DragDropEffects was not listed in the AllowedEffects..
        /// </summary>
        internal static string Error_EffectsNotAllowed {
            get {
                return ResourceManager.GetString("Error_EffectsNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The enumeration either has ended or has not yet been started..
        /// </summary>
        internal static string Error_EnumerationNotReady {
            get {
                return ResourceManager.GetString("Error_EnumerationNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The gesture data is of type &apos;{0}&apos; but it must be at least of type &apos;{1}&apos;.  When setting a new gesture data you must use the same or more derived type as the gesture data you are replacing..
        /// </summary>
        internal static string Error_IncompatibleGestureData {
            get {
                return ResourceManager.GetString("Error_IncompatibleGestureData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PositionReference contained in each reference value must be the same..
        /// </summary>
        internal static string Error_IncompatiblePositionReference {
            get {
                return ResourceManager.GetString("Error_IncompatiblePositionReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FocusedTask context item is set automatically when a task is focused through the BeginFocus method on the task.  Do not set this item yourself..
        /// </summary>
        internal static string Error_IncorrectFocusedTask {
            get {
                return ResourceManager.GetString("Error_IncorrectFocusedTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An object &apos;{0}&apos; has published a service of type &apos;{1}&apos; but the service instance was returned as &apos;{2}&apos;..
        /// </summary>
        internal static string Error_IncorrectServiceType {
            get {
                return ResourceManager.GetString("Error_IncorrectServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type passed must derive from &apos;{0}&apos;..
        /// </summary>
        internal static string Error_IncorrectTypePassed {
            get {
                return ResourceManager.GetString("Error_IncorrectTypePassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index &apos;{0}&apos; is beyond the bounds of the array..
        /// </summary>
        internal static string Error_InvalidArrayIndex {
            get {
                return ResourceManager.GetString("Error_InvalidArrayIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FactoryType must be set to a type that derives from NewItemFactory..
        /// </summary>
        internal static string Error_InvalidFactoryType {
            get {
                return ResourceManager.GetString("Error_InvalidFactoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The extension &apos;{0}&apos; returned an invalid value from RedirectParent.  If you do not want to support redirection, return the original parent..
        /// </summary>
        internal static string Error_InvalidRedirectParent {
            get {
                return ResourceManager.GetString("Error_InvalidRedirectParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input type must be &apos;{0}&apos;.
        /// </summary>
        internal static string Error_InvalidToolboxExampleFactoryType {
            get {
                return ResourceManager.GetString("Error_InvalidToolboxExampleFactoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;LocalAssemblyName&apos; cannot be changed..
        /// </summary>
        internal static string Error_LocalAssemblyNameChanged {
            get {
                return ResourceManager.GetString("Error_LocalAssemblyNameChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid editing context is necessary to perform this operation..
        /// </summary>
        internal static string Error_MissingContext {
            get {
                return ResourceManager.GetString("Error_MissingContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot create an instance of an object if CreationType has not been set.  Set CreationType to a valid type and try again..
        /// </summary>
        internal static string Error_NoCreationType {
            get {
                return ResourceManager.GetString("Error_NoCreationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature requires a DesignerView to exist in the context, but none could be found..
        /// </summary>
        internal static string Error_NoDesignerView {
            get {
                return ResourceManager.GetString("Error_NoDesignerView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ExecuteEventArgs Data property does not contain an object of type &apos;{0}&apos;.  This command cannot be invoked unless the correct data is passed..
        /// </summary>
        internal static string Error_NoGestureData {
            get {
                return ResourceManager.GetString("Error_NoGestureData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; does not have a value..
        /// </summary>
        internal static string Error_NoPropertyValue {
            get {
                return ResourceManager.GetString("Error_NoPropertyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method &apos;{0}&apos; has returned null, but that is not allowed in the implementation..
        /// </summary>
        internal static string Error_NullImplementation {
            get {
                return ResourceManager.GetString("Error_NullImplementation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An object &apos;{0}&apos; has published a service of type &apos;{1}&apos; but the returned instance was null..
        /// </summary>
        internal static string Error_NullService {
            get {
                return ResourceManager.GetString("Error_NullService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object &apos;{0}&apos; has already been activated..
        /// </summary>
        internal static string Error_ObjectAlreadyActive {
            get {
                return ResourceManager.GetString("Error_ObjectAlreadyActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object &apos;{0}&apos; is not currently activated..
        /// </summary>
        internal static string Error_ObjectNotActive {
            get {
                return ResourceManager.GetString("Error_ObjectNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An object of type &apos;{0}&apos; does not support parenting an object of type &apos;{1}&apos;..
        /// </summary>
        internal static string Error_ParentNotSupported {
            get {
                return ResourceManager.GetString("Error_ParentNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; is read only..
        /// </summary>
        internal static string Error_PropertyIsReadOnly {
            get {
                return ResourceManager.GetString("Error_PropertyIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; does not exist on objects of type &apos;{1}&apos;..
        /// </summary>
        internal static string Error_PropertyNotFound {
            get {
                return ResourceManager.GetString("Error_PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected e.Parameter to be non-null and to be a PropertyValue. CommandParameter should have a Binding to the PropertyValue..
        /// </summary>
        internal static string Error_PropertyValueEditor_InvalidDialogValueEditorCommandInvocation {
            get {
                return ResourceManager.GetString("Error_PropertyValueEditor_InvalidDialogValueEditorCommandInvocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected PropertyValue.OwningEditor to be non-null and to be a subclass of PropertyValueEditorDialogBase..
        /// </summary>
        internal static string Error_PropertyValueEditor_InvalidDialogValueEditorEditorValue {
            get {
                return ResourceManager.GetString("Error_PropertyValueEditor_InvalidDialogValueEditorEditorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While resolving the service &apos;{0}&apos; a recursive request was made for the same service..
        /// </summary>
        internal static string Error_RecursionResolvingService {
            get {
                return ResourceManager.GetString("Error_RecursionResolvingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature requires service &apos;{0}&apos; to be present, but it could not be located..
        /// </summary>
        internal static string Error_RequiredService {
            get {
                return ResourceManager.GetString("Error_RequiredService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation of the attribute table has failed..
        /// </summary>
        internal static string Error_TableValidationFailed {
            get {
                return ResourceManager.GetString("Error_TableValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current tool already has a task focused.  Only one task can be focused at a time..
        /// </summary>
        internal static string Error_TaskAlreadyFocused {
            get {
                return ResourceManager.GetString("Error_TaskAlreadyFocused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tool &apos;{0}&apos; is already active in this editing context.  You cannot activate the same instance of a task tool more than once..
        /// </summary>
        internal static string Error_ToolAlreadyActive {
            get {
                return ResourceManager.GetString("Error_ToolAlreadyActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MemberDescriptors of type &apos;{0}&apos; are not supported..
        /// </summary>
        internal static string Error_UnknownMemberDescriptor {
            get {
                return ResourceManager.GetString("Error_UnknownMemberDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member named &apos;{0}&apos; was found as both a property and an event on type &apos;{1}&apos;.  Members with the same name are not supported..
        /// </summary>
        internal static string Error_ValidationAmbiguousMember {
            get {
                return ResourceManager.GetString("Error_ValidationAmbiguousMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member named &apos;{0}&apos; does not exist on type &apos;{1}&apos;..
        /// </summary>
        internal static string Error_ValidationNoMatchingMember {
            get {
                return ResourceManager.GetString("Error_ValidationNoMatchingMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get of Value failed..
        /// </summary>
        internal static string Error_ValueGetFailed {
            get {
                return ResourceManager.GetString("Error_ValueGetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set of Value failed..
        /// </summary>
        internal static string Error_ValueSetFailed {
            get {
                return ResourceManager.GetString("Error_ValueSetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The visual &apos;{0}&apos; is not being shown in the designer..
        /// </summary>
        internal static string Error_VisualNotInDesigner {
            get {
                return ResourceManager.GetString("Error_VisualNotInDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new &apos;{0}&apos;.
        /// </summary>
        internal static string ToolDescription_CreateInstance {
            get {
                return ResourceManager.GetString("ToolDescription_CreateInstance", resourceCulture);
            }
        }
    }
}
