// Decompiled with JetBrains decompiler
// Type: Microsoft.Expression.DesignModel.Markup.Xml.Token
// Assembly: Microsoft.Expression.Markup, Version=4.0.20525.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
// MVID: C29AFBAF-B4D4-48F4-95E5-A72FADF351FB
// Assembly location: C:\Program Files (x86)\Microsoft Expression\Blend 4\Microsoft.Expression.Markup.dll

namespace Microsoft.Expression.DesignModel.Markup.Xml
{
  internal enum Token
  {
    None,
    MarkupDeclaration,
    StartCharacterData,
    CharacterData,
    CharLiteral,
    EndOfTag,
    EndOfEndTag,
    EndOfSimpleTag,
    MultiLineComment,
    StartProcessingInstruction,
    ProcessingInstructions,
    StartOfClosingTag,
    StartOfTag,
    StartStringLiteral,
    StringLiteral,
    LiteralComment,
    StartLiteralComment,
    LiteralContentString,
    Assign,
    Colon,
    IllegalCharacter,
    CharacterEntity,
    GeneralEntityReference,
    ParameterEntityReference,
    LeftBracket,
    RightBracket,
    Identifier,
    Whitespace,
    LeftParen,
    RightParen,
    Comma,
    Or,
    Plus,
    Star,
    QuestionMark,
    Percent,
    Pound,
    PUBLIC,
    SYSTEM,
    ANY,
    EMPTY,
    CDATA,
    NOTATION,
    NDATA,
    ID,
    IDREF,
    IDREFS,
    ENTITY,
    ENTITIES,
    NMTOKEN,
    NMTOKENS,
    REQUIRED,
    IMPLIED,
    PCDATA,
    FIXED,
    EndOfLine,
    EndOfFile,
  }
}
