// Decompiled with JetBrains decompiler
// Type: Microsoft.Expression.DesignModel.Markup.XamlErrorCode
// Assembly: Microsoft.Expression.Markup, Version=4.0.20525.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
// MVID: C29AFBAF-B4D4-48F4-95E5-A72FADF351FB
// Assembly location: C:\Program Files (x86)\Microsoft Expression\Blend 4\Microsoft.Expression.Markup.dll

namespace Microsoft.Expression.DesignModel.Markup
{
  public enum XamlErrorCode
  {
    XmlError,
    NoRootElement,
    UnexpectedRootType,
    MultipleRootElements,
    NoDefaultNamespace,
    InvalidClassName,
    UnrecognizedXmlnsPrefix,
    DuplicateXmlnsPrefix,
    UnrecognizedTypeName,
    InaccessibleType,
    InnerTypesNotSupported,
    NestedPropertiesNotSupported,
    UnrecognizedOrInaccessibleMember,
    PropertyIsNotWritable,
    CannotDetermineMemberTargetType,
    UnrecognizedDesignTimeProperty,
    AmbiguousDesignTimeProperty,
    MissingTypeName,
    InvalidPrefixQualifiedTypeName,
    InvalidTypeQualifiedMemberName,
    PrimitiveTypeWithNoValue,
    AbstractTypeWithNoValue,
    ArrayPropertyRequiresExplicitPropertyTag,
    NoAccessibleConstructor,
    IncorrectNumberOfConstructorArguments,
    ConstructorArgumentDeclaredTypeDoesNotMatchProperty,
    TypeIsNotNullable,
    TypeDoesNotSupportInlineXml,
    CannotConvertFromString,
    UnrecognizedName,
    RepeatedName,
    RepeatedKey,
    UnrecognizedAttribute,
    UnrecognizedXmlAttribute,
    AttributeValidAtRootOnly,
    AttributeRequiresExplicitClassAttribute,
    AttributeValidInSpecificContainerOnly,
    MissingProperty,
    PropertyElementWithNoValue,
    PropertySetMultipleTimes,
    SingleValuedPropertySetMultipleTimes,
    MemberNotDependencyProperty,
    MemberNotRoutedEvent,
    TypeInitializationException,
    LocalPropertyDoesNotApply,
    AttachedPropertyDoesNotApply,
    MissingDictionaryKey,
    UnexpectedValueType,
    UnexpectedChildType,
    ParentTypeDoesNotSupportChildren,
    MissingMarkupExtensionName,
    MissingArgumentName,
    UnexpectedPositionalArgument,
    UnexpectedEnd,
    InvalidMarkupExtensionArguments,
    UnexpectedCharacter,
    InvalidPropertyPathSyntax,
    InvalidClrNamespaceUri,
    InvalidXmlSpace,
    CDataNotSupported,
    MismatchedType,
    UnknownError,
    NextAvailableErrorCode,
  }
}
