//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionStringTable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionStringTable() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shopdrawing.Framework.Properties.ExceptionStringTable", typeof(ExceptionStringTable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddService must be called with an instance of the specified type..
        /// </summary>
        internal static string AddServiceMustBeCalledWithAnInstanceOfSpecifiedType {
            get {
                return ResourceManager.GetString("AddServiceMustBeCalledWithAnInstanceOfSpecifiedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The assembly does not exist..
        /// </summary>
        internal static string AssemblyDoesNotExist {
            get {
                return ResourceManager.GetString("AssemblyDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add an atomic undo unit to undo manager..
        /// </summary>
        internal static string CannotAddAtomicUnitToUndoManager {
            get {
                return ResourceManager.GetString("CannotAddAtomicUnitToUndoManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add undo units to an undo container that is already closed..
        /// </summary>
        internal static string CannotAddUndoUnitsToAnUndoContainerThatIsAlreadyClosed {
            get {
                return ResourceManager.GetString("CannotAddUndoUnitsToAnUndoContainerThatIsAlreadyClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot clear the undo stack from within an open undo container..
        /// </summary>
        internal static string CannotClearFromWithinAnOpenUndoContainer {
            get {
                return ResourceManager.GetString("CannotClearFromWithinAnOpenUndoContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create an undo transaction while performing an undo operation..
        /// </summary>
        internal static string CannotCreateTransactionDuringUndo {
            get {
                return ResourceManager.GetString("CannotCreateTransactionDuringUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create or access Workspaces folder: {0}.
        /// </summary>
        internal static string CannotCreateWorkspacesFolder {
            get {
                return ResourceManager.GetString("CannotCreateWorkspacesFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot end a closed undo unit container..
        /// </summary>
        internal static string CannotEndClosedUndoContainer {
            get {
                return ResourceManager.GetString("CannotEndClosedUndoContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot end undo unit containers out of order..
        /// </summary>
        internal static string CannotEndUndoContainersOutOfOrder {
            get {
                return ResourceManager.GetString("CannotEndUndoContainersOutOfOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot end without an open undo unit container..
        /// </summary>
        internal static string CannotEndWithoutOpenUndoContainer {
            get {
                return ResourceManager.GetString("CannotEndWithoutOpenUndoContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a TypeConverter for type {0} while parsing ConfigurationObject..
        /// </summary>
        internal static string CannotFindATypeConverterForType {
            get {
                return ResourceManager.GetString("CannotFindATypeConverterForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change a sealed undo unit container..
        /// </summary>
        internal static string CannotModifySealedUndoUnitContainer {
            get {
                return ResourceManager.GetString("CannotModifySealedUndoUnitContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot nest calls to add undo units..
        /// </summary>
        internal static string CannotNestAdds {
            get {
                return ResourceManager.GetString("CannotNestAdds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot reach here..
        /// </summary>
        internal static string CannotReachHere {
            get {
                return ResourceManager.GetString("CannotReachHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot redo from within an open undo unit container..
        /// </summary>
        internal static string CannotRedoFromWithinAnOpenUndoContainer {
            get {
                return ResourceManager.GetString("CannotRedoFromWithinAnOpenUndoContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot undo from within an open undo unit container..
        /// </summary>
        internal static string CannotUndoFromWithinAnOpenUndoContainer {
            get {
                return ResourceManager.GetString("CannotUndoFromWithinAnOpenUndoContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can only set FocusScopePriority on an element that is a FocusScope..
        /// </summary>
        internal static string CanOnlySetFocusScopePriorityOnAnElementThatIsAFocusScope {
            get {
                return ResourceManager.GetString("CanOnlySetFocusScopePriorityOnAnElementThatIsAFocusScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t register a dependency on a nonexistent task..
        /// </summary>
        internal static string CantRegisterADependencyOnANonexistentTask {
            get {
                return ResourceManager.GetString("CantRegisterADependencyOnANonexistentTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t register a dependency on a task at a lower priority than yourself..
        /// </summary>
        internal static string CantRegisterADependencyOnATaskAtALowerPriorityThanYourself {
            get {
                return ResourceManager.GetString("CantRegisterADependencyOnATaskAtALowerPriorityThanYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t register two tasks with the same name..
        /// </summary>
        internal static string CantRegisterTwoTasksWithSameName {
            get {
                return ResourceManager.GetString("CantRegisterTwoTasksWithSameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t remove a task that other tasks depend on..
        /// </summary>
        internal static string CantRemoveATaskThatOtherTasksDependOn {
            get {
                return ResourceManager.GetString("CantRemoveATaskThatOtherTasksDependOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConvertBack not implemented on MarginConverter..
        /// </summary>
        internal static string ConvertBackNotImplementedOnMarginConverter {
            get {
                return ResourceManager.GetString("ConvertBackNotImplementedOnMarginConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert not implemented on MarginConverter..
        /// </summary>
        internal static string ConvertNotImplementedOnMarginConverter {
            get {
                return ResourceManager.GetString("ConvertNotImplementedOnMarginConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document &quot;{0}&quot; is already open..
        /// </summary>
        internal static string DocumentAlreadyOpen {
            get {
                return ResourceManager.GetString("DocumentAlreadyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document &quot;{0}&quot; is read-only..
        /// </summary>
        internal static string DocumentIsReadOnly {
            get {
                return ResourceManager.GetString("DocumentIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document &quot;{0}&quot; is not included in the open document list..
        /// </summary>
        internal static string DocumentNotIncludedInOpenDocumentList {
            get {
                return ResourceManager.GetString("DocumentNotIncludedInOpenDocumentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not defined for this converter..
        /// </summary>
        internal static string Error_ConverterFunctionNotDefined {
            get {
                return ResourceManager.GetString("Error_ConverterFunctionNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converter requires {0} source parameters..
        /// </summary>
        internal static string Error_InsufficientSourceParameters {
            get {
                return ResourceManager.GetString("Error_InsufficientSourceParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converter requires {0} type parameters..
        /// </summary>
        internal static string Error_InsufficientTypeParameters {
            get {
                return ResourceManager.GetString("Error_InsufficientTypeParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target type at offset {0} must extend {1}..
        /// </summary>
        internal static string Error_TargetAtOffsetNotExtendingType {
            get {
                return ResourceManager.GetString("Error_TargetAtOffsetNotExtendingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target type must extend {0}..
        /// </summary>
        internal static string Error_TargetNotExtendingType {
            get {
                return ResourceManager.GetString("Error_TargetNotExtendingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value at offset {0} must be of type {1}..
        /// </summary>
        internal static string Error_ValueAtOffsetNotOfType {
            get {
                return ResourceManager.GetString("Error_ValueAtOffsetNotOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be of type {0}..
        /// </summary>
        internal static string Error_ValueNotOfType {
            get {
                return ResourceManager.GetString("Error_ValueNotOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be of type &apos;System.String&apos;.
        /// </summary>
        internal static string ImportClickGestureConverterInvalidArgument {
            get {
                return ResourceManager.GetString("ImportClickGestureConverterInvalidArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid gesture format, should be in the form &apos;Event&apos; or &apos;KeyModifier+Event&apos;.
        /// </summary>
        internal static string ImportClickGestureConverterInvalidGestureFormat {
            get {
                return ResourceManager.GetString("ImportClickGestureConverterInvalidGestureFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to importer added more than once.
        /// </summary>
        internal static string ImportDuplicateImporter {
            get {
                return ResourceManager.GetString("ImportDuplicateImporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filePath cannot be empty, it should be a path to a full file or a file extension.
        /// </summary>
        internal static string ImportFilePathCannotBeEmpty {
            get {
                return ResourceManager.GetString("ImportFilePathCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The imaging library was not found.  Re-installing the application may fix this problem..
        /// </summary>
        internal static string ImportImagingLibraryIsMissing {
            get {
                return ResourceManager.GetString("ImportImagingLibraryIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid InputGesture Type, found &apos;{0}&apos; expected &apos;{1}&apos;..
        /// </summary>
        internal static string ImportInputGestureInvalidType {
            get {
                return ResourceManager.GetString("ImportInputGestureInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid number of importers were found to handle this file. Found &apos;{0}&apos;, expected 1.
        /// </summary>
        internal static string ImportInvalidNumberOfImporters {
            get {
                return ResourceManager.GetString("ImportInvalidNumberOfImporters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must supply defaultOptions of Type Microsoft.Expression.Framework.Import.LayeredImages.Psd.PsdImportOptions.
        /// </summary>
        internal static string ImportOptionsIncorrectType {
            get {
                return ResourceManager.GetString("ImportOptionsIncorrectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No codec was found for the Photoshop file format.    Re-installing the application may fix this problem..
        /// </summary>
        internal static string ImportPsdCodecIsMissing {
            get {
                return ResourceManager.GetString("ImportPsdCodecIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create renderer.
        /// </summary>
        internal static string ImportUnableToCreateRenderer {
            get {
                return ResourceManager.GetString("ImportUnableToCreateRenderer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read the specified file.
        /// </summary>
        internal static string ImportUnableToReadFile {
            get {
                return ResourceManager.GetString("ImportUnableToReadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid TargetSubProperty..
        /// </summary>
        internal static string InvalidTargetSubProperty {
            get {
                return ResourceManager.GetString("InvalidTargetSubProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item is already present in list..
        /// </summary>
        internal static string ItemIsAlreadyPresentInList {
            get {
                return ResourceManager.GetString("ItemIsAlreadyPresentInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method or operation is not implemented..
        /// </summary>
        internal static string MethodOrOperationIsNotImplemented {
            get {
                return ResourceManager.GetString("MethodOrOperationIsNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ConvertBack for ValueToIcon converter..
        /// </summary>
        internal static string NoConvertBackForValueToIconConverter {
            get {
                return ResourceManager.GetString("NoConvertBackForValueToIconConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palette name &apos;{0}&apos; must be registered before adding palette..
        /// </summary>
        internal static string PaletteNameMustBeRegisteredBeforeAddingPalette {
            get {
                return ResourceManager.GetString("PaletteNameMustBeRegisteredBeforeAddingPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The redo stack is empty..
        /// </summary>
        internal static string RedoStackIsEmpty {
            get {
                return ResourceManager.GetString("RedoStackIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A SwitchConverter cannot be used for a two-way bind..
        /// </summary>
        internal static string SwitchConverterIsOneWay {
            get {
                return ResourceManager.GetString("SwitchConverterIsOneWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A string cannot be transformed to a UIElement..
        /// </summary>
        internal static string UIElementToStringConverterNoInverse {
            get {
                return ResourceManager.GetString("UIElementToStringConverterNoInverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The undo stack is empty..
        /// </summary>
        internal static string UndoStackIsEmpty {
            get {
                return ResourceManager.GetString("UndoStackIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected brush type {0}..
        /// </summary>
        internal static string UnexpectedBrushType {
            get {
                return ResourceManager.GetString("UnexpectedBrushType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected drawing type {0}..
        /// </summary>
        internal static string UnexpectedDrawingType {
            get {
                return ResourceManager.GetString("UnexpectedDrawingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected image source type {0}..
        /// </summary>
        internal static string UnexpectedImageSourceType {
            get {
                return ResourceManager.GetString("UnexpectedImageSourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a string..
        /// </summary>
        internal static string ValueMustBeAString {
            get {
                return ResourceManager.GetString("ValueMustBeAString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view is already open..
        /// </summary>
        internal static string ViewAlreadyOpen {
            get {
                return ResourceManager.GetString("ViewAlreadyOpen", resourceCulture);
            }
        }
    }
}
