//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopdrawing.Resources.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shopdrawing.Resources.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_addarrow {
            get {
                object obj = ResourceManager.GetObject("cursor_addarrow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_centerpoint {
            get {
                object obj = ResourceManager.GetObject("cursor_centerpoint", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_convert {
            get {
                object obj = ResourceManager.GetObject("cursor_convert", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_convertpoint {
            get {
                object obj = ResourceManager.GetObject("cursor_convertpoint", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_convertsegment {
            get {
                object obj = ResourceManager.GetObject("cursor_convertsegment", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_converttangent {
            get {
                object obj = ResourceManager.GetObject("cursor_converttangent", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_crosshair {
            get {
                object obj = ResourceManager.GetObject("cursor_crosshair", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_databinding_detail {
            get {
                object obj = ResourceManager.GetObject("cursor_databinding_detail", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_databinding_detail_add {
            get {
                object obj = ResourceManager.GetObject("cursor_databinding_detail_add", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_databinding_master {
            get {
                object obj = ResourceManager.GetObject("cursor_databinding_master", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_databinding_master_add {
            get {
                object obj = ResourceManager.GetObject("cursor_databinding_master_add", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_designtimeresize1 {
            get {
                object obj = ResourceManager.GetObject("cursor_designtimeresize1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_designtimeresize2 {
            get {
                object obj = ResourceManager.GetObject("cursor_designtimeresize2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_designtimeresize3 {
            get {
                object obj = ResourceManager.GetObject("cursor_designtimeresize3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_dupwedge {
            get {
                object obj = ResourceManager.GetObject("cursor_dupwedge", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_eyedropper {
            get {
                object obj = ResourceManager.GetObject("cursor_eyedropper", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_gradientredefine {
            get {
                object obj = ResourceManager.GetObject("cursor_gradientredefine", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_gridrowselect {
            get {
                object obj = ResourceManager.GetObject("cursor_gridrowselect", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_marqueeselect {
            get {
                object obj = ResourceManager.GetObject("cursor_marqueeselect", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_minusarrow {
            get {
                object obj = ResourceManager.GetObject("cursor_minusarrow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_nodrop {
            get {
                object obj = ResourceManager.GetObject("cursor_nodrop", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_numericadjust2 {
            get {
                object obj = ResourceManager.GetObject("cursor_numericadjust2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_numericaladjust {
            get {
                object obj = ResourceManager.GetObject("cursor_numericaladjust", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_orbit {
            get {
                object obj = ResourceManager.GetObject("cursor_orbit", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_paintbucket {
            get {
                object obj = ResourceManager.GetObject("cursor_paintbucket", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_pan {
            get {
                object obj = ResourceManager.GetObject("cursor_pan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_pen {
            get {
                object obj = ResourceManager.GetObject("cursor_pen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_penadjust {
            get {
                object obj = ResourceManager.GetObject("cursor_penadjust", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_pencil {
            get {
                object obj = ResourceManager.GetObject("cursor_pencil", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_penclose {
            get {
                object obj = ResourceManager.GetObject("cursor_penclose", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_pendelete {
            get {
                object obj = ResourceManager.GetObject("cursor_pendelete", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_penextent {
            get {
                object obj = ResourceManager.GetObject("cursor_penextent", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_peninsert {
            get {
                object obj = ResourceManager.GetObject("cursor_peninsert", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_penjoin {
            get {
                object obj = ResourceManager.GetObject("cursor_penjoin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_penstart {
            get {
                object obj = ResourceManager.GetObject("cursor_penstart", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_pentangent {
            get {
                object obj = ResourceManager.GetObject("cursor_pentangent", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_propertypicker {
            get {
                object obj = ResourceManager.GetObject("cursor_propertypicker", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_relocate {
            get {
                object obj = ResourceManager.GetObject("cursor_relocate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_resize1 {
            get {
                object obj = ResourceManager.GetObject("cursor_resize1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_resize2 {
            get {
                object obj = ResourceManager.GetObject("cursor_resize2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_resize3 {
            get {
                object obj = ResourceManager.GetObject("cursor_resize3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_resize4 {
            get {
                object obj = ResourceManager.GetObject("cursor_resize4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_rotate1 {
            get {
                object obj = ResourceManager.GetObject("cursor_rotate1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_rotate10 {
            get {
                object obj = ResourceManager.GetObject("cursor_rotate10", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_rotate11 {
            get {
                object obj = ResourceManager.GetObject("cursor_rotate11", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_rotate12 {
            get {
                object obj = ResourceManager.GetObject("cursor_rotate12", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_rotate13 {
            get {
                object obj = ResourceManager.GetObject("cursor_rotate13", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_rotate14 {
            get {
                object obj = ResourceManager.GetObject("cursor_rotate14", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_rotate15 {
            get {
                object obj = ResourceManager.GetObject("cursor_rotate15", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_rotate16 {
            get {
                object obj = ResourceManager.GetObject("cursor_rotate16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_rotate2 {
            get {
                object obj = ResourceManager.GetObject("cursor_rotate2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_rotate3 {
            get {
                object obj = ResourceManager.GetObject("cursor_rotate3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_rotate4 {
            get {
                object obj = ResourceManager.GetObject("cursor_rotate4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_rotate5 {
            get {
                object obj = ResourceManager.GetObject("cursor_rotate5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_rotate6 {
            get {
                object obj = ResourceManager.GetObject("cursor_rotate6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_rotate7 {
            get {
                object obj = ResourceManager.GetObject("cursor_rotate7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_rotate8 {
            get {
                object obj = ResourceManager.GetObject("cursor_rotate8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_rotate9 {
            get {
                object obj = ResourceManager.GetObject("cursor_rotate9", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_roundedrect {
            get {
                object obj = ResourceManager.GetObject("cursor_roundedrect", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_selectelement {
            get {
                object obj = ResourceManager.GetObject("cursor_selectelement", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_selection {
            get {
                object obj = ResourceManager.GetObject("cursor_selection", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_skew1 {
            get {
                object obj = ResourceManager.GetObject("cursor_skew1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_skew2 {
            get {
                object obj = ResourceManager.GetObject("cursor_skew2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_skew3 {
            get {
                object obj = ResourceManager.GetObject("cursor_skew3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_skew4 {
            get {
                object obj = ResourceManager.GetObject("cursor_skew4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_skew5 {
            get {
                object obj = ResourceManager.GetObject("cursor_skew5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_skew6 {
            get {
                object obj = ResourceManager.GetObject("cursor_skew6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_skew7 {
            get {
                object obj = ResourceManager.GetObject("cursor_skew7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_skew8 {
            get {
                object obj = ResourceManager.GetObject("cursor_skew8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_subselectbezier {
            get {
                object obj = ResourceManager.GetObject("cursor_subselectbezier", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_subselectelement {
            get {
                object obj = ResourceManager.GetObject("cursor_subselectelement", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_subselection {
            get {
                object obj = ResourceManager.GetObject("cursor_subselection", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_subselectmove {
            get {
                object obj = ResourceManager.GetObject("cursor_subselectmove", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_subselectpoint {
            get {
                object obj = ResourceManager.GetObject("cursor_subselectpoint", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_subselectsegment {
            get {
                object obj = ResourceManager.GetObject("cursor_subselectsegment", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_xrotate {
            get {
                object obj = ResourceManager.GetObject("cursor_xrotate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_xtranslate {
            get {
                object obj = ResourceManager.GetObject("cursor_xtranslate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_yrotate {
            get {
                object obj = ResourceManager.GetObject("cursor_yrotate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_ytranslate {
            get {
                object obj = ResourceManager.GetObject("cursor_ytranslate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_zoomin {
            get {
                object obj = ResourceManager.GetObject("cursor_zoomin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_zoomout {
            get {
                object obj = ResourceManager.GetObject("cursor_zoomout", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_zrotate {
            get {
                object obj = ResourceManager.GetObject("cursor_zrotate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_ztranslate {
            get {
                object obj = ResourceManager.GetObject("cursor_ztranslate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pickwhip_cursor {
            get {
                object obj = ResourceManager.GetObject("pickwhip_cursor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Shopdrawing {
            get {
                object obj = ResourceManager.GetObject("Shopdrawing", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
