// Decompiled with JetBrains decompiler
// Type: MS.Internal.Design.Markup.Error
// Assembly: Microsoft.Expression.Code, Version=4.0.20525.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
// MVID: 3445693A-E9B1-4B68-8C1A-000C20F2A3F8
// Assembly location: C:\Program Files (x86)\Microsoft Expression\Blend 4\Microsoft.Expression.Code.dll

namespace MS.Internal.Design.Markup
{
  internal enum Error
  {
    UnterminatedString = 101,
    UnescapedOpenTag = 102,
    UnterminatedCharacterData = 103,
    UnterminatedComment = 104,
    CommentedEndedWithDoubleHyphenBangGreaterThan = 105,
    CommentWithDoubleHyphen = 106,
    NoSuchNamedEntity = 107,
    MissingSemicolonInEntity = 108,
    BadDecimalDigit = 109,
    BadHexDigit = 110,
    EntityOverflow = 111,
    ExpectedDifferentToken = 112,
    UnterminatedProcessingInstruction = 113,
    UnterminatedXmlText = 114,
    AmbiguousTypeReference = 201,
    UnableToLoadAssemlby = 202,
    InvalidXmlnsDefinitionAttribute = 203,
    EmptyXmlnsDeclaration = 204,
    UnexpectedToken = 301,
    IllegalWhitespaceInIdentifier = 302,
    ExpectedIdentifier = 303,
    ExpectedString = 304,
    ClosingTagMismatch = 305,
    MaxDepthReached = 306,
    ExpectedWhitespace = 307,
    UnexpectedAttribute = 401,
    UnexpectedElement = 402,
    UnexpectedText = 403,
    InvalidIgnorableAttribute = 404,
    InvalidProcessContentAttribute = 405,
    AtLeastOneChoiceMustBePresent = 406,
    InvalidRequiresSyntax = 407,
    RequiresRequired = 408,
    MultipleElementsInRootAlternateContent = 409,
    FallbackMustBeLast = 410,
    OnlyOneFallbackAllowed = 411,
    InvalidXamlName = 412,
    UndefinedProperty = 413,
    UndefinedType = 414,
    UndefinedAttachableProperty = 415,
    AttributeAlreadyDefined = 416,
    InvalidClrNamespaceSyntax = 417,
    AssemblyNotPartOfProject = 418,
    NamespaceNotFoundInAssembly = 419,
    PropertyElementSyntaxNotLegalHere = 420,
    PropertyIsNotAttachable = 421,
    InvalidXmlSpace = 422,
    InvalidXmlAttribute = 423,
    XDataCanHaveOnlyOneElement = 424,
    InvalidTypeArgumentSyntax = 425,
    InvalidMustUnderstandAttribute = 426,
    NoDefaultAssembly = 427,
    PropertyAlreadySet = 501,
    ContentNotSupported = 502,
    CollectionElementTypeMismatch = 503,
    PropertyTypeMismatch = 504,
    TypeIsNotAMarkupExtensions = 505,
    IncorrectNumberOfCtorArguments = 506,
    ObjectIsNotConstructable = 507,
    StringNotAllowedInDictionary = 508,
    PropertiesInMiddleOfContent = 509,
    ExpectedPropertyValue = 510,
    KeyOnlyAllowedInDictionary = 511,
    NonFatal = 1000,
    XamlAttributeOnlyValidOnRoot = 1101,
    UnknownXamlAttribute = 1102,
    LastError = 1103,
  }
}
