//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Expression.Blend {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringTable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringTable() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Expression.Blend.StringTable", typeof(StringTable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Animation.
        /// </summary>
        internal static string AnimationWorkspaceName {
            get {
                return ResourceManager.GetString("AnimationWorkspaceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading the assembly &quot;{0}&quot;.
        ///{1}.
        /// </summary>
        internal static string ApplicationAssemblyLoadErrorDialogMessage {
            get {
                return ResourceManager.GetString("ApplicationAssemblyLoadErrorDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Exception.
        /// </summary>
        internal static string ApplicationSecurityExceptionDialogTitle {
            get {
                return ResourceManager.GetString("ApplicationSecurityExceptionDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner exception: {0}.
        /// </summary>
        internal static string ApplicationTargetInvocationDialogMessage {
            get {
                return ResourceManager.GetString("ApplicationTargetInvocationDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Invocation Exception.
        /// </summary>
        internal static string ApplicationTargetInvocationDialogTitle {
            get {
                return ResourceManager.GetString("ApplicationTargetInvocationDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Expression Blend 4.
        /// </summary>
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}.
        /// </summary>
        internal static string ApplicationTitleFormatWithProjectName {
            get {
                return ResourceManager.GetString("ApplicationTitleFormatWithProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blend has encountered an unrecoverable internal error and must close.
        ///
        ///Do you want to save your work?.
        /// </summary>
        internal static string ApplicationUnrecoverableErrorDialogMessage {
            get {
                return ResourceManager.GetString("ApplicationUnrecoverableErrorDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy Into Source DrawingBrush.
        /// </summary>
        internal static string CopyToResourceMenu {
            get {
                return ResourceManager.GetString("CopyToResourceMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Design.
        /// </summary>
        internal static string DesignWorkspaceName {
            get {
                return ResourceManager.GetString("DesignWorkspaceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find in Fi_les.
        /// </summary>
        internal static string FindInFiles {
            get {
                return ResourceManager.GetString("FindInFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression Blend could not load one or more of the installed extensions from {0}. Please uninstall and then reinstall the latest version of the extensions.
        ///
        ///See the Results panel for more information.
        ///.
        /// </summary>
        internal static string MefCompositionException {
            get {
                return ResourceManager.GetString("MefCompositionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A_lign.
        /// </summary>
        internal static string MenuBarArrangeMenuAlign {
            get {
                return ResourceManager.GetString("MenuBarArrangeMenuAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Bottom Edges.
        /// </summary>
        internal static string MenuBarArrangeMenuAlignBottom {
            get {
                return ResourceManager.GetString("MenuBarArrangeMenuAlignBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Horizontal Centers.
        /// </summary>
        internal static string MenuBarArrangeMenuAlignCenterHorizontally {
            get {
                return ResourceManager.GetString("MenuBarArrangeMenuAlignCenterHorizontally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Left Edges.
        /// </summary>
        internal static string MenuBarArrangeMenuAlignLeft {
            get {
                return ResourceManager.GetString("MenuBarArrangeMenuAlignLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Vertical Centers.
        /// </summary>
        internal static string MenuBarArrangeMenuAlignMiddleVertically {
            get {
                return ResourceManager.GetString("MenuBarArrangeMenuAlignMiddleVertically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Right Edges.
        /// </summary>
        internal static string MenuBarArrangeMenuAlignRight {
            get {
                return ResourceManager.GetString("MenuBarArrangeMenuAlignRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Top Edges.
        /// </summary>
        internal static string MenuBarArrangeMenuAlignTop {
            get {
                return ResourceManager.GetString("MenuBarArrangeMenuAlignTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Si_ze.
        /// </summary>
        internal static string MenuBarArrangeMenuAutoSize {
            get {
                return ResourceManager.GetString("MenuBarArrangeMenuAutoSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Both.
        /// </summary>
        internal static string MenuBarArrangeMenuAutoSizeBoth {
            get {
                return ResourceManager.GetString("MenuBarArrangeMenuAutoSizeBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Fill.
        /// </summary>
        internal static string MenuBarArrangeMenuAutoSizeFill {
            get {
                return ResourceManager.GetString("MenuBarArrangeMenuAutoSizeFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Height.
        /// </summary>
        internal static string MenuBarArrangeMenuAutoSizeHeight {
            get {
                return ResourceManager.GetString("MenuBarArrangeMenuAutoSizeHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Width.
        /// </summary>
        internal static string MenuBarArrangeMenuAutoSizeWidth {
            get {
                return ResourceManager.GetString("MenuBarArrangeMenuAutoSizeWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Flip.
        /// </summary>
        internal static string MenuBarArrangeMenuFlip {
            get {
                return ResourceManager.GetString("MenuBarArrangeMenuFlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Horizontal.
        /// </summary>
        internal static string MenuBarArrangeMenuFlipHorizontal {
            get {
                return ResourceManager.GetString("MenuBarArrangeMenuFlipHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Vertical.
        /// </summary>
        internal static string MenuBarArrangeMenuFlipVertical {
            get {
                return ResourceManager.GetString("MenuBarArrangeMenuFlipVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Group.
        /// </summary>
        internal static string MenuBarArrangeMenuGroup {
            get {
                return ResourceManager.GetString("MenuBarArrangeMenuGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Group Into.
        /// </summary>
        internal static string MenuBarArrangeMenuGroupInto {
            get {
                return ResourceManager.GetString("MenuBarArrangeMenuGroupInto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Height.
        /// </summary>
        internal static string MenuBarArrangeMenuMakeSameHeight {
            get {
                return ResourceManager.GetString("MenuBarArrangeMenuMakeSameHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Size.
        /// </summary>
        internal static string MenuBarArrangeMenuMakeSameSize {
            get {
                return ResourceManager.GetString("MenuBarArrangeMenuMakeSameSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Width.
        /// </summary>
        internal static string MenuBarArrangeMenuMakeSameWidth {
            get {
                return ResourceManager.GetString("MenuBarArrangeMenuMakeSameWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O_rder.
        /// </summary>
        internal static string MenuBarArrangeMenuOrder {
            get {
                return ResourceManager.GetString("MenuBarArrangeMenuOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bring F_orward.
        /// </summary>
        internal static string MenuBarArrangeMenuOrderBringForward {
            get {
                return ResourceManager.GetString("MenuBarArrangeMenuOrderBringForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bring to _Front.
        /// </summary>
        internal static string MenuBarArrangeMenuOrderBringToFront {
            get {
                return ResourceManager.GetString("MenuBarArrangeMenuOrderBringToFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send B_ackward.
        /// </summary>
        internal static string MenuBarArrangeMenuOrderSendBackward {
            get {
                return ResourceManager.GetString("MenuBarArrangeMenuOrderSendBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to _Back.
        /// </summary>
        internal static string MenuBarArrangeMenuOrderSendToBack {
            get {
                return ResourceManager.GetString("MenuBarArrangeMenuOrderSendToBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Make Same.
        /// </summary>
        internal static string MenuBarArrangeMenuSize {
            get {
                return ResourceManager.GetString("MenuBarArrangeMenuSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Ungroup.
        /// </summary>
        internal static string MenuBarArrangeMenuUngroup {
            get {
                return ResourceManager.GetString("MenuBarArrangeMenuUngroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy Annotations as Text.
        /// </summary>
        internal static string MenuBarCopyAnnotationsInDocumentAsText {
            get {
                return ResourceManager.GetString("MenuBarCopyAnnotationsInDocumentAsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create _Annotation.
        /// </summary>
        internal static string MenuBarCreateAnnotation {
            get {
                return ResourceManager.GetString("MenuBarCreateAnnotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete Annotations.
        /// </summary>
        internal static string MenuBarDeleteAnnotationsInDocument {
            get {
                return ResourceManager.GetString("MenuBarDeleteAnnotationsInDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        internal static string MenuBarEdit {
            get {
                return ResourceManager.GetString("MenuBarEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C_omment Selection.
        /// </summary>
        internal static string MenuBarEditMenuCommentSelection {
            get {
                return ResourceManager.GetString("MenuBarEditMenuCommentSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy.
        /// </summary>
        internal static string MenuBarEditMenuCopy {
            get {
                return ResourceManager.GetString("MenuBarEditMenuCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cu_t.
        /// </summary>
        internal static string MenuBarEditMenuCut {
            get {
                return ResourceManager.GetString("MenuBarEditMenuCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete.
        /// </summary>
        internal static string MenuBarEditMenuDelete {
            get {
                return ResourceManager.GetString("MenuBarEditMenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Find....
        /// </summary>
        internal static string MenuBarEditMenuFind {
            get {
                return ResourceManager.GetString("MenuBarEditMenuFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find _Next.
        /// </summary>
        internal static string MenuBarEditMenuFindNext {
            get {
                return ResourceManager.GetString("MenuBarEditMenuFindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Go To....
        /// </summary>
        internal static string MenuBarEditMenuGoTo {
            get {
                return ResourceManager.GetString("MenuBarEditMenuGoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Paste.
        /// </summary>
        internal static string MenuBarEditMenuPaste {
            get {
                return ResourceManager.GetString("MenuBarEditMenuPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Redo.
        /// </summary>
        internal static string MenuBarEditMenuRedo {
            get {
                return ResourceManager.GetString("MenuBarEditMenuRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R_eplace....
        /// </summary>
        internal static string MenuBarEditMenuReplace {
            get {
                return ResourceManager.GetString("MenuBarEditMenuReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select _All.
        /// </summary>
        internal static string MenuBarEditMenuSelectAll {
            get {
                return ResourceManager.GetString("MenuBarEditMenuSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Select None.
        /// </summary>
        internal static string MenuBarEditMenuSelectNone {
            get {
                return ResourceManager.GetString("MenuBarEditMenuSelectNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se_t as Startup.
        /// </summary>
        internal static string MenuBarEditMenuSetSetStartupScene {
            get {
                return ResourceManager.GetString("MenuBarEditMenuSetSetStartupScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unco_mment Selection.
        /// </summary>
        internal static string MenuBarEditMenuUncommentSelection {
            get {
                return ResourceManager.GetString("MenuBarEditMenuUncommentSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Undo.
        /// </summary>
        internal static string MenuBarEditMenuUndo {
            get {
                return ResourceManager.GetString("MenuBarEditMenuUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        internal static string MenuBarFile {
            get {
                return ResourceManager.GetString("MenuBarFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close Document.
        /// </summary>
        internal static string MenuBarFileMenuClose {
            get {
                return ResourceManager.GetString("MenuBarFileMenuClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close All _Documents.
        /// </summary>
        internal static string MenuBarFileMenuCloseAll {
            get {
                return ResourceManager.GetString("MenuBarFileMenuCloseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Ot_her Documents.
        /// </summary>
        internal static string MenuBarFileMenuCloseOther {
            get {
                return ResourceManager.GetString("MenuBarFileMenuCloseOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        internal static string MenuBarFileMenuExit {
            get {
                return ResourceManager.GetString("MenuBarFileMenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Import....
        /// </summary>
        internal static string MenuBarFileMenuImport {
            get {
                return ResourceManager.GetString("MenuBarFileMenuImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Import Adobe Illustrator File....
        /// </summary>
        internal static string MenuBarFileMenuImportIllustrator {
            get {
                return ResourceManager.GetString("MenuBarFileMenuImportIllustrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_mport Adobe Photoshop File....
        /// </summary>
        internal static string MenuBarFileMenuImportPhotoshop {
            get {
                return ResourceManager.GetString("MenuBarFileMenuImportPhotoshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New Item....
        /// </summary>
        internal static string MenuBarFileMenuNewItem {
            get {
                return ResourceManager.GetString("MenuBarFileMenuNewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne_w Project....
        /// </summary>
        internal static string MenuBarFileMenuNewProject {
            get {
                return ResourceManager.GetString("MenuBarFileMenuNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open Project/Solution....
        /// </summary>
        internal static string MenuBarFileMenuOpenProjectSolution {
            get {
                return ResourceManager.GetString("MenuBarFileMenuOpenProjectSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        internal static string MenuBarFileMenuSave {
            get {
                return ResourceManager.GetString("MenuBarFileMenuSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save A_ll.
        /// </summary>
        internal static string MenuBarFileMenuSaveAll {
            get {
                return ResourceManager.GetString("MenuBarFileMenuSaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Recent Projects.
        /// </summary>
        internal static string MenuBarFileRecentProjects {
            get {
                return ResourceManager.GetString("MenuBarFileRecentProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Co_ntrol.
        /// </summary>
        internal static string MenuBarFormatMenuEditControl {
            get {
                return ResourceManager.GetString("MenuBarFormatMenuEditControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit a _Copy....
        /// </summary>
        internal static string MenuBarFormatMenuEditCopyStyle {
            get {
                return ResourceManager.GetString("MenuBarFormatMenuEditCopyStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit C_urrent.
        /// </summary>
        internal static string MenuBarFormatMenuEditExistingStyle {
            get {
                return ResourceManager.GetString("MenuBarFormatMenuEditExistingStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit C_urrent.
        /// </summary>
        internal static string MenuBarFormatMenuEditExistingTemplate {
            get {
                return ResourceManager.GetString("MenuBarFormatMenuEditExistingTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Apply Resource.
        /// </summary>
        internal static string MenuBarFormatMenuEditLocalResource {
            get {
                return ResourceManager.GetString("MenuBarFormatMenuEditLocalResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create _Empty....
        /// </summary>
        internal static string MenuBarFormatMenuEditNewStyle {
            get {
                return ResourceManager.GetString("MenuBarFormatMenuEditNewStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit _Style.
        /// </summary>
        internal static string MenuBarFormatMenuEditStyleMenuName {
            get {
                return ResourceManager.GetString("MenuBarFormatMenuEditStyleMenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Additi_onal Styles.
        /// </summary>
        internal static string MenuBarFormatMenuEditStyles {
            get {
                return ResourceManager.GetString("MenuBarFormatMenuEditStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit Template.
        /// </summary>
        internal static string MenuBarFormatMenuEditTemplateMenuName {
            get {
                return ResourceManager.GetString("MenuBarFormatMenuEditTemplateMenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_dit Additional Templates.
        /// </summary>
        internal static string MenuBarFormatMenuEditTemplates {
            get {
                return ResourceManager.GetString("MenuBarFormatMenuEditTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit _Text.
        /// </summary>
        internal static string MenuBarFormatMenuEditText {
            get {
                return ResourceManager.GetString("MenuBarFormatMenuEditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide A_ll.
        /// </summary>
        internal static string MenuBarFormatMenuHideAllObjects {
            get {
                return ResourceManager.GetString("MenuBarFormatMenuHideAllObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Hide Selection.
        /// </summary>
        internal static string MenuBarFormatMenuHideObjects {
            get {
                return ResourceManager.GetString("MenuBarFormatMenuHideObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock _All.
        /// </summary>
        internal static string MenuBarFormatMenuLockAllObjects {
            get {
                return ResourceManager.GetString("MenuBarFormatMenuLockAllObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loc_k.
        /// </summary>
        internal static string MenuBarFormatMenuLockMenuName {
            get {
                return ResourceManager.GetString("MenuBarFormatMenuLockMenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Lock Selection.
        /// </summary>
        internal static string MenuBarFormatMenuLockObjects {
            get {
                return ResourceManager.GetString("MenuBarFormatMenuLockObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show _All.
        /// </summary>
        internal static string MenuBarFormatMenuShowAllObjects {
            get {
                return ResourceManager.GetString("MenuBarFormatMenuShowAllObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Show Selection.
        /// </summary>
        internal static string MenuBarFormatMenuShowObjects {
            get {
                return ResourceManager.GetString("MenuBarFormatMenuShowObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Unlock All.
        /// </summary>
        internal static string MenuBarFormatMenuUnlockAllObjects {
            get {
                return ResourceManager.GetString("MenuBarFormatMenuUnlockAllObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Visibility.
        /// </summary>
        internal static string MenuBarFormatMenuVisibilityMenuName {
            get {
                return ResourceManager.GetString("MenuBarFormatMenuVisibilityMenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        internal static string MenuBarHelp {
            get {
                return ResourceManager.GetString("MenuBarHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About {0}.
        /// </summary>
        internal static string MenuBarHelpMenuAbout {
            get {
                return ResourceManager.GetString("MenuBarHelpMenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acti_vate Product.
        /// </summary>
        internal static string MenuBarHelpMenuActivateProduct {
            get {
                return ResourceManager.GetString("MenuBarHelpMenuActivateProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Enter Product Key.
        /// </summary>
        internal static string MenuBarHelpMenuEnterProductKey {
            get {
                return ResourceManager.GetString("MenuBarHelpMenuEnterProductKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Customer Experience Improvement Program.
        /// </summary>
        internal static string MenuBarHelpMenuFeedbackOptions {
            get {
                return ResourceManager.GetString("MenuBarHelpMenuFeedbackOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _User Guide.
        /// </summary>
        internal static string MenuBarHelpMenuHelpTopics {
            get {
                return ResourceManager.GetString("MenuBarHelpMenuHelpTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Keyboard Shortcuts.
        /// </summary>
        internal static string MenuBarHelpMenuKeyboardShortcuts {
            get {
                return ResourceManager.GetString("MenuBarHelpMenuKeyboardShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Privacy Statement.
        /// </summary>
        internal static string MenuBarHelpMenuPrivacyStatement {
            get {
                return ResourceManager.GetString("MenuBarHelpMenuPrivacyStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Register Expression Blend.
        /// </summary>
        internal static string MenuBarHelpMenuRegisterProduct {
            get {
                return ResourceManager.GetString("MenuBarHelpMenuRegisterProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression Blend _SDK User Guide.
        /// </summary>
        internal static string MenuBarHelpMenuSdkHelpTopics {
            get {
                return ResourceManager.GetString("MenuBarHelpMenuSdkHelpTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Online Community.
        /// </summary>
        internal static string MenuBarHelpMenuWebsite {
            get {
                return ResourceManager.GetString("MenuBarHelpMenuWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Expression Community Home.
        /// </summary>
        internal static string MenuBarHelpMenuWebsiteCommunityHome {
            get {
                return ResourceManager.GetString("MenuBarHelpMenuWebsiteCommunityHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Community News, Blogs, and Events.
        /// </summary>
        internal static string MenuBarHelpMenuWebsiteCommunityNews {
            get {
                return ResourceManager.GetString("MenuBarHelpMenuWebsiteCommunityNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Downloads.
        /// </summary>
        internal static string MenuBarHelpMenuWebsiteDownloads {
            get {
                return ResourceManager.GetString("MenuBarHelpMenuWebsiteDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Gallery.
        /// </summary>
        internal static string MenuBarHelpMenuWebsiteGallery {
            get {
                return ResourceManager.GetString("MenuBarHelpMenuWebsiteGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Inside Expression.
        /// </summary>
        internal static string MenuBarHelpMenuWebsiteInsideExpression {
            get {
                return ResourceManager.GetString("MenuBarHelpMenuWebsiteInsideExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Learn.
        /// </summary>
        internal static string MenuBarHelpMenuWebsiteLearn {
            get {
                return ResourceManager.GetString("MenuBarHelpMenuWebsiteLearn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Online Forums.
        /// </summary>
        internal static string MenuBarHelpMenuWebsiteOnlineForums {
            get {
                return ResourceManager.GetString("MenuBarHelpMenuWebsiteOnlineForums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xpression Blend Team Blog.
        /// </summary>
        internal static string MenuBarHelpMenuWebsiteTeamBlog {
            get {
                return ResourceManager.GetString("MenuBarHelpMenuWebsiteTeamBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Welcome Screen.
        /// </summary>
        internal static string MenuBarHelpMenuWelcomeScreen {
            get {
                return ResourceManager.GetString("MenuBarHelpMenuWelcomeScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin _Active Container.
        /// </summary>
        internal static string MenuBarLockInsertionPoint {
            get {
                return ResourceManager.GetString("MenuBarLockInsertionPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Object.
        /// </summary>
        internal static string MenuBarObject {
            get {
                return ResourceManager.GetString("MenuBarObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Convert to Motion Path.
        /// </summary>
        internal static string MenuBarObjectMenuConvertToMotionPath {
            get {
                return ResourceManager.GetString("MenuBarObjectMenuConvertToMotionPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to _Path.
        /// </summary>
        internal static string MenuBarObjectMenuConvertToPath {
            get {
                return ResourceManager.GetString("MenuBarObjectMenuConvertToPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M_ake Clipping Path.
        /// </summary>
        internal static string MenuBarObjectMenuMakeClippingPath {
            get {
                return ResourceManager.GetString("MenuBarObjectMenuMakeClippingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Make Compound Path.
        /// </summary>
        internal static string MenuBarObjectMenuMakeCompoundPath {
            get {
                return ResourceManager.GetString("MenuBarObjectMenuMakeCompoundPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make _Layout Path.
        /// </summary>
        internal static string MenuBarObjectMenuMakeLayoutPath {
            get {
                return ResourceManager.GetString("MenuBarObjectMenuMakeLayoutPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Path.
        /// </summary>
        internal static string MenuBarObjectMenuPath {
            get {
                return ResourceManager.GetString("MenuBarObjectMenuPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Release Compound Path.
        /// </summary>
        internal static string MenuBarObjectMenuReleaseCompoundPath {
            get {
                return ResourceManager.GetString("MenuBarObjectMenuReleaseCompoundPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relea_se Clipping Path.
        /// </summary>
        internal static string MenuBarObjectMenuRemoveClippingPath {
            get {
                return ResourceManager.GetString("MenuBarObjectMenuRemoveClippingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Project.
        /// </summary>
        internal static string MenuBarProject {
            get {
                return ResourceManager.GetString("MenuBarProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add E_xisting Project....
        /// </summary>
        internal static string MenuBarProjectAddExistingProject {
            get {
                return ResourceManager.GetString("MenuBarProjectAddExistingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add _Existing Website....
        /// </summary>
        internal static string MenuBarProjectAddExistingWebsite {
            get {
                return ResourceManager.GetString("MenuBarProjectAddExistingWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Ne_w Project....
        /// </summary>
        internal static string MenuBarProjectAddNewProject {
            get {
                return ResourceManager.GetString("MenuBarProjectAddNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Add Existing Item....
        /// </summary>
        internal static string MenuBarProjectMenuAddExistingItem {
            get {
                return ResourceManager.GetString("MenuBarProjectMenuAddExistingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New _Item....
        /// </summary>
        internal static string MenuBarProjectMenuAddNewItem {
            get {
                return ResourceManager.GetString("MenuBarProjectMenuAddNewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add _Project Reference.
        /// </summary>
        internal static string MenuBarProjectMenuAddProjectReference {
            get {
                return ResourceManager.GetString("MenuBarProjectMenuAddProjectReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Re_ference....
        /// </summary>
        internal static string MenuBarProjectMenuAddReference {
            get {
                return ResourceManager.GetString("MenuBarProjectMenuAddReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Application _Outside Browser.
        /// </summary>
        internal static string MenuBarProjectMenuEnableOutOfBrowser {
            get {
                return ResourceManager.GetString("MenuBarProjectMenuEnableOutOfBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Preview Application Outside Browser.
        /// </summary>
        internal static string MenuBarProjectMenuEnablePreviewOutOfBrowser {
            get {
                return ResourceManager.GetString("MenuBarProjectMenuEnablePreviewOutOfBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Link to Existing Item....
        /// </summary>
        internal static string MenuBarProjectMenuLinkToExistingItem {
            get {
                return ResourceManager.GetString("MenuBarProjectMenuLinkToExistingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add _New Folder.
        /// </summary>
        internal static string MenuBarProjectMenuNewFolder {
            get {
                return ResourceManager.GetString("MenuBarProjectMenuNewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Requires _Elevated Permission.
        /// </summary>
        internal static string MenuBarProjectMenuRequireElevatedPermissions {
            get {
                return ResourceManager.GetString("MenuBarProjectMenuRequireElevatedPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil_verlight Project Settings.
        /// </summary>
        internal static string MenuBarProjectMenuSilverlightFlyoutMenu {
            get {
                return ResourceManager.GetString("MenuBarProjectMenuSilverlightFlyoutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Application _Library Caching.
        /// </summary>
        internal static string MenuBarProjectMenuUsePlatformExtensions {
            get {
                return ResourceManager.GetString("MenuBarProjectMenuUsePlatformExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tools.
        /// </summary>
        internal static string MenuBarTools {
            get {
                return ResourceManager.GetString("MenuBarTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C_lear Part Assignment.
        /// </summary>
        internal static string MenuBarToolsMenuClearPartAssignment {
            get {
                return ResourceManager.GetString("MenuBarToolsMenuClearPartAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Combine.
        /// </summary>
        internal static string MenuBarToolsMenuCombine {
            get {
                return ResourceManager.GetString("MenuBarToolsMenuCombine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy State _To.
        /// </summary>
        internal static string MenuBarToolsMenuCopyAllStateProperties {
            get {
                return ResourceManager.GetString("MenuBarToolsMenuCopyAllStateProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Selected P_roperties of State To.
        /// </summary>
        internal static string MenuBarToolsMenuCopySelectedStateProperties {
            get {
                return ResourceManager.GetString("MenuBarToolsMenuCopySelectedStateProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Divide.
        /// </summary>
        internal static string MenuBarToolsMenuDivide {
            get {
                return ResourceManager.GetString("MenuBarToolsMenuDivide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit Brush Resource.
        /// </summary>
        internal static string MenuBarToolsMenuEditTileBrush {
            get {
                return ResourceManager.GetString("MenuBarToolsMenuEditTileBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exclude Overlap.
        /// </summary>
        internal static string MenuBarToolsMenuExcludeOverlap {
            get {
                return ResourceManager.GetString("MenuBarToolsMenuExcludeOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Intersect.
        /// </summary>
        internal static string MenuBarToolsMenuIntersect {
            get {
                return ResourceManager.GetString("MenuBarToolsMenuIntersect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Into Component _Screen....
        /// </summary>
        internal static string MenuBarToolsMenuMakeCompositionScreen {
            get {
                return ResourceManager.GetString("MenuBarToolsMenuMakeCompositionScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Make Into Control....
        /// </summary>
        internal static string MenuBarToolsMenuMakeControl {
            get {
                return ResourceManager.GetString("MenuBarToolsMenuMakeControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make _DrawingBrush Resource....
        /// </summary>
        internal static string MenuBarToolsMenuMakeDrawingBrush {
            get {
                return ResourceManager.GetString("MenuBarToolsMenuMakeDrawingBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make _Image 3D.
        /// </summary>
        internal static string MenuBarToolsMenuMakeImage3D {
            get {
                return ResourceManager.GetString("MenuBarToolsMenuMakeImage3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make _ImageBrush Resource....
        /// </summary>
        internal static string MenuBarToolsMenuMakeImageBrush {
            get {
                return ResourceManager.GetString("MenuBarToolsMenuMakeImageBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Into Part....
        /// </summary>
        internal static string MenuBarToolsMenuMakePart {
            get {
                return ResourceManager.GetString("MenuBarToolsMenuMakePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma_ke Brush Resource.
        /// </summary>
        internal static string MenuBarToolsMenuMakeTileBrush {
            get {
                return ResourceManager.GetString("MenuBarToolsMenuMakeTileBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Into _UserControl....
        /// </summary>
        internal static string MenuBarToolsMenuMakeUserControl {
            get {
                return ResourceManager.GetString("MenuBarToolsMenuMakeUserControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make _VideoBrush Resource....
        /// </summary>
        internal static string MenuBarToolsMenuMakeVideoBrush {
            get {
                return ResourceManager.GetString("MenuBarToolsMenuMakeVideoBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make _VisualBrush Resource....
        /// </summary>
        internal static string MenuBarToolsMenuMakeVisualBrush {
            get {
                return ResourceManager.GetString("MenuBarToolsMenuMakeVisualBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Subtract.
        /// </summary>
        internal static string MenuBarToolsMenuSubtract {
            get {
                return ResourceManager.GetString("MenuBarToolsMenuSubtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Unite.
        /// </summary>
        internal static string MenuBarToolsMenuUnite {
            get {
                return ResourceManager.GetString("MenuBarToolsMenuUnite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Name Interactive Elements.
        /// </summary>
        internal static string MenuBarToolsNameInteractiveElements {
            get {
                return ResourceManager.GetString("MenuBarToolsNameInteractiveElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Options....
        /// </summary>
        internal static string MenuBarToolsOptions {
            get {
                return ResourceManager.GetString("MenuBarToolsOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Font Manager....
        /// </summary>
        internal static string MenuBarToolsSetupFontEmbedding {
            get {
                return ResourceManager.GetString("MenuBarToolsSetupFontEmbedding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        internal static string MenuBarView {
            get {
                return ResourceManager.GetString("MenuBarView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Actual Size.
        /// </summary>
        internal static string MenuBarViewMenuActualSize {
            get {
                return ResourceManager.GetString("MenuBarViewMenuActualSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Active Document _View.
        /// </summary>
        internal static string MenuBarViewMenuCycle {
            get {
                return ResourceManager.GetString("MenuBarViewMenuCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Design View.
        /// </summary>
        internal static string MenuBarViewMenuDesign {
            get {
                return ResourceManager.GetString("MenuBarViewMenuDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Document _View.
        /// </summary>
        internal static string MenuBarViewMenuDocumentMenu {
            get {
                return ResourceManager.GetString("MenuBarViewMenuDocumentMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fi_t All.
        /// </summary>
        internal static string MenuBarViewMenuFitToAll {
            get {
                return ResourceManager.GetString("MenuBarViewMenuFitToAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Fit to Screen.
        /// </summary>
        internal static string MenuBarViewMenuFitToScreen {
            get {
                return ResourceManager.GetString("MenuBarViewMenuFitToScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Fit Selection.
        /// </summary>
        internal static string MenuBarViewMenuFitToSelection {
            get {
                return ResourceManager.GetString("MenuBarViewMenuFitToSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Active _Container.
        /// </summary>
        internal static string MenuBarViewMenuShowActiveContainer {
            get {
                return ResourceManager.GetString("MenuBarViewMenuShowActiveContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show _Handles.
        /// </summary>
        internal static string MenuBarViewMenuShowAdorners {
            get {
                return ResourceManager.GetString("MenuBarViewMenuShowAdorners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Alignment A_dorners.
        /// </summary>
        internal static string MenuBarViewMenuShowAlignmentAdorners {
            get {
                return ResourceManager.GetString("MenuBarViewMenuShowAlignmentAdorners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show A_nnotations.
        /// </summary>
        internal static string MenuBarViewMenuShowAnnotations {
            get {
                return ResourceManager.GetString("MenuBarViewMenuShowAnnotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Object _Boundaries.
        /// </summary>
        internal static string MenuBarViewMenuShowBoundaries {
            get {
                return ResourceManager.GetString("MenuBarViewMenuShowBoundaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply _Projections.
        /// </summary>
        internal static string MenuBarViewMenuShowObjectsWithProjections {
            get {
                return ResourceManager.GetString("MenuBarViewMenuShowObjectsWithProjections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show S_election Preview.
        /// </summary>
        internal static string MenuBarViewMenuShowSelectionPreview {
            get {
                return ResourceManager.GetString("MenuBarViewMenuShowSelectionPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Split View.
        /// </summary>
        internal static string MenuBarViewMenuSplit {
            get {
                return ResourceManager.GetString("MenuBarViewMenuSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Swap Design and XAML Panes.
        /// </summary>
        internal static string MenuBarViewMenuSplitDesignOnTop {
            get {
                return ResourceManager.GetString("MenuBarViewMenuSplitDesignOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrange Panes _Horizontally.
        /// </summary>
        internal static string MenuBarViewMenuSplitHorizontally {
            get {
                return ResourceManager.GetString("MenuBarViewMenuSplitHorizontally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Split View Orientation.
        /// </summary>
        internal static string MenuBarViewMenuSplitMenu {
            get {
                return ResourceManager.GetString("MenuBarViewMenuSplitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrange Panes _Vertically.
        /// </summary>
        internal static string MenuBarViewMenuSplitVertically {
            get {
                return ResourceManager.GetString("MenuBarViewMenuSplitVertically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide 3D _Lights.
        /// </summary>
        internal static string MenuBarViewMenuToggleLights {
            get {
                return ResourceManager.GetString("MenuBarViewMenuToggleLights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _XAML View.
        /// </summary>
        internal static string MenuBarViewMenuXaml {
            get {
                return ResourceManager.GetString("MenuBarViewMenuXaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom _In.
        /// </summary>
        internal static string MenuBarViewMenuZoomIn {
            get {
                return ResourceManager.GetString("MenuBarViewMenuZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom _Out.
        /// </summary>
        internal static string MenuBarViewMenuZoomOut {
            get {
                return ResourceManager.GetString("MenuBarViewMenuZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Window.
        /// </summary>
        internal static string MenuBarWindow {
            get {
                return ResourceManager.GetString("MenuBarWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Active _Workspace.
        /// </summary>
        internal static string MenuBarWindowCycleWorkspaces {
            get {
                return ResourceManager.GetString("MenuBarWindowCycleWorkspaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All _Workspaces....
        /// </summary>
        internal static string MenuBarWindowMenuAllWorkspaces {
            get {
                return ResourceManager.GetString("MenuBarWindowMenuAllWorkspaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto_Hide All Panels.
        /// </summary>
        internal static string MenuBarWindowMenuHideWorkspacePalettes {
            get {
                return ResourceManager.GetString("MenuBarWindowMenuHideWorkspacePalettes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Manage Workspaces....
        /// </summary>
        internal static string MenuBarWindowMenuManageWorkspaces {
            get {
                return ResourceManager.GetString("MenuBarWindowMenuManageWorkspaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Reset Current Workspace.
        /// </summary>
        internal static string MenuBarWindowMenuResetWorkspace {
            get {
                return ResourceManager.GetString("MenuBarWindowMenuResetWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sa_ve as New Workspace....
        /// </summary>
        internal static string MenuBarWindowMenuSaveAsNewWorkspace {
            get {
                return ResourceManager.GetString("MenuBarWindowMenuSaveAsNewWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Empty).
        /// </summary>
        internal static string MenuBarWindowsEmpty {
            get {
                return ResourceManager.GetString("MenuBarWindowsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _All Windows....
        /// </summary>
        internal static string MenuBarWindowsMore {
            get {
                return ResourceManager.GetString("MenuBarWindowsMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Workspaces.
        /// </summary>
        internal static string MenuBarWindowsWorkspace {
            get {
                return ResourceManager.GetString("MenuBarWindowsWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Move Into Source DrawingBrush.
        /// </summary>
        internal static string MoveToResourceMenu {
            get {
                return ResourceManager.GetString("MoveToResourceMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some optimized rendering is supported by your system and video drivers..
        /// </summary>
        internal static string RenderTierOneMessage {
            get {
                return ResourceManager.GetString("RenderTierOneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full optimized rendering is supported by your system and video drivers..
        /// </summary>
        internal static string RenderTierTwoMessage {
            get {
                return ResourceManager.GetString("RenderTierTwoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimized rendering is not supported by your system or video drivers..
        /// </summary>
        internal static string RenderTierZeroMessage {
            get {
                return ResourceManager.GetString("RenderTierZeroMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered a license that adds SketchFlow support. Restart Expression Blend to start using SketchFlow..
        /// </summary>
        internal static string SketchFlowEnabled {
            get {
                return ResourceManager.GetString("SketchFlowEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression dark.
        /// </summary>
        internal static string ThemeNameExpressionDark {
            get {
                return ResourceManager.GetString("ThemeNameExpressionDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression light.
        /// </summary>
        internal static string ThemeNameExpressionLight {
            get {
                return ResourceManager.GetString("ThemeNameExpressionLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        internal static string ThemeNameWindows {
            get {
                return ResourceManager.GetString("ThemeNameWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The prereleased version of this product has expired.
        ///You must update to a newer release..
        /// </summary>
        internal static string TimebombExpiredMessage {
            get {
                return ResourceManager.GetString("TimebombExpiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired version.
        /// </summary>
        internal static string TimebombExpiredTitle {
            get {
                return ResourceManager.GetString("TimebombExpiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Microsoft Expression Blend.
        /// </summary>
        internal static string WelcomeScreenTitle {
            get {
                return ResourceManager.GetString("WelcomeScreenTitle", resourceCulture);
            }
        }
    }
}
